=== Shujin001/Exams/5thWT/XML/library.dtd
<!ELEMENT Library (Profile, Books)>
<!ELEMENT Profile (Address, Email, Phone, Company)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ATTLIST Profile ID CDATA #REQUIRED>
<!ATTLIST Company name CDATA #REQUIRED> 
<!ELEMENT Books (Book)+>
<!ELEMENT Book (Name, ISBN, Author)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT Author (#PCDATA)>

=== Shujin001/Exams/5thWT/XML/library.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Library SYSTEM "library.dtd">
<Library>
    <Profile ID="10">
        <Address>Shankhamul, Kathmandu, Nepal</Address>
        <Email>library@email.com</Email>
        <Phone>+977 01 4460441</Phone>
        <Company name="Nagarjuna College"/>
    </Profile>
    <Books>
        <Book>
            <Name>Web Technology</Name>
            <ISBN>ISBN2000</ISBN> 
            <Author>Prof. Dr. Subarna Shakya</Author>
        </Book>
        <Book>
            <Name>Database Management System</Name>
            <ISBN>ISBN3000</ISBN> 
            <Author>Assistant Prof. Kumar Prashun</Author>
        </Book>
    </Books>
</Library>
