<?xml version="1.0" encoding="UTF-8" standalone="yes"?><!-- Declaration -->

<!--DTD (Document Type Definition)
    - CDATA: Character Data
    - PCDATA: Parsable Character Data

    Internal DTD
-->
<!DOCTYPE note [
    <!ELEMENT note (to, from, heading, body)>
    <!ELEMENT to (#PCDATA)>
    <!ELEMENT from (#PCDATA)>
    <!ELEMENT heading (#PCDATA)>
    <!ELEMENT body (#PCDATA)>
]>
<!-- XML (eXtensible Markup Language)-->
<note>
    <to>Tove</to>
    <from>Jani</from>
    <heading>Remainder</heading>
    <body> Don't forget me this weekend </body>
</note>