=== Shujin001/Exams/Lab3/q3/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="book_records">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="first" type="xs:string"/>
                                        <xs:element name="middle" type="xs:string"/>
                                        <xs:element name="last" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[^@]+@[^\.]+\..+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <xs:element name="author" type="xs:string" maxOccurs="unbounded"/>
                            
                            <xs:element name="page_no" type="xs:integer" minOccurs="0"/>
                            
                            <xs:element name="price">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:maxInclusive value="600"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="isbn" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Shujin001/Exams/Lab3/q3/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<book_records xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books.xsd">
    <book isbn="978-3-16-148410-0">
        <name>
            <first>John</first>
            <middle>Ram</middle>
            <last>Doe</last>
        </name>
        <email>example@example.com</email>
        <author>Author One</author>
        <author>Author Two</author>
        <page_no>450</page_no>
        <price>550.00</price>
    </book>
</book_records>
